### ISSUE TITLE
Use ES6 Proxies when available

### ISSUE THREAD

**Issue by phated** [iceddev/rawr#7]
As per discussion with @briancavalier in IRC

> in a world with ES6 Proxies, Rawr could simply be a Proxy that intercepts all method calls and translates them into rpc calls (it could even do that before the SMD arrives)
> var rawr = Rawr.create(socket);
> var promiseForResult = rawr.doStuff();

Look into http://atomizejs.github.io/ for proxy transpiling

Ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by monteslu** [comment]
done
